// swift-tools-version: 5.6
// Generated by X3M spm-compat-publisher. Unofficial compatibility package for
// https://github.com/AppLovin/AppLovin-MAX-Swift-Package-IronSource.git tag 905000000.0.0: the LevelPlay SDK dependency points to
// https://github.com/ironsource-mobile/LevelPlay-Swift-Package.git instead of https://github.com/ironsource-mobile/Unity-Mediation-iAds-Swift-Package.git.
// Not affiliated with or endorsed by AppLovin.

import PackageDescription

let package = Package(
    name: "AppLovinMediationIronSourceAdapter",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "AppLovinMediationIronSourceAdapter", targets: ["AppLovinMediationIronSourceAdapterTarget"]),
    ],
    dependencies: [
        .package(url: "https://github.com/AppLovin/AppLovin-MAX-Swift-Package.git", from: "13.0.0"),
        .package(url: "https://github.com/ironsource-mobile/LevelPlay-Swift-Package.git", exact: "9.5.0"),
    ],
    targets: [
        .target(
            name: "AppLovinMediationIronSourceAdapterTarget",
            dependencies: [
                .target(name: "AppLovinMediationIronSourceAdapter"),
                .product(name: "AppLovinSDK", package: "AppLovin-MAX-Swift-Package"),
                .product(name: "UnityMediationSDK", package: "LevelPlay-Swift-Package"),
            ]
        ),
        .binaryTarget(
            name: "AppLovinMediationIronSourceAdapter",
            url: "https://artifacts.applovin.com/ios/com/applovin/mediation/ironsource-adapter/AppLovinMediationIronSourceAdapter-9.5.0.0.0.zip",
            checksum: "f36ff9f315b1e7a7bab314e1403a7d57e101defb09b8d45d12b36fb80ea74552"
        ),
    ]
)
